# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Test Python Package

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install pep517
      run: |
        python -m pip install --upgrade pip
        python -m pip install pep517 attrs --user

    - name: Build a binary wheel and a source tarball
      run: |
        python -m pep517.build --source --binary --out-dir dist/ .
        pwd
        ls

#    - name: Publish distribution to Test PyPI
#      uses: pypa/gh-action-pypi-publish@master
#      with:
#        password: ${{ secrets.audacity_scripting_test_pypi_password }}
#        repository_url: https://test.pypi.org/legacy/
