# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build Test and Upload Python Package

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install build requirements
      run: |
        python -m pip install pep517 attrs

    - name: Build a binary wheel and a source tarball
      run: |
        python -m pep517.build --source --binary --out-dir dist/ .

    - name: Install new build
      run: |
        python -m pip install dist/audacity_scripting*.whl

    - name: Install test requirements
      run: |
        python -m pip install flake8 pytest pytest-pep8 parameterized
        pip freeze

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest --pep8

#    - name: Publish distribution to Test PyPI
#      uses: pypa/gh-action-pypi-publish@master
#      with:
#        password: ${{ secrets.audacity_scripting_test_pypi_password }}
#        repository_url: https://test.pypi.org/legacy/
